//
// Created by Tre on 7/5/2020.
//

#ifndef OGLEXPERIMENTS_ENGINECONSTANTS_H
#define OGLEXPERIMENTS_ENGINECONSTANTS_H

namespace EngineConstants {
    float constexpr COORDINATE_GRID_SCALE = 0.1f;
    int constexpr GRID_VERTICE_COUNT = 1.0f / COORDINATE_GRID_SCALE * 2 * 2;
    int constexpr GRID_VERTICE_BUFFER_SIZE = GRID_VERTICE_COUNT * 2 * 2;
}

#endif //OGLEXPERIMENTS_ENGINECONSTANTS_H
